### ISSUE TITLE
potential build issue: Invoking "cmake" failed

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaMPC/MAVs#111]
```
Step 5/9 : RUN /bin/bash -c 'source /opt/ros/kinetic/setup.bash; cd /home/$USERNAME/MAVs/ros/src; sudo rosdep init; rosdep update; catkin_init_workspace; cd ..; catkin_make'     && echo "source /home/$USERNAME/MAVs/ros/devel/setup.bash" >> /home/$USERNAME/.bashrc     && echo 'alias julia='/opt/julia-d386e40c17/bin/julia'' >> ~/.bashrc     && echo 'export PATH="$PATH:/opt/julia-d386e40c17/bin"' >>  ~/.bashrc
 ---> Running in 0c86179fd405
Wrote /etc/ros/rosdep/sources.list.d/20-default.list
Recommended: please run

	rosdep update

reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index.yaml
Add distro "groovy"
Add distro "hydro"
Add distro "indigo"
Add distro "jade"
Add distro "kinetic"
Add distro "lunar"
Add distro "melodic"
updated cache in /home/mavs/.ros/rosdep/sources.cache
File "/home/mavs/MAVs/ros/src/CMakeLists.txt" already existsCMake Error: The current CMakeCache.txt directory /home/mavs/MAVs/ros/build/CMakeCache.txt is different than the directory /home/febbo/Documents/workspace/MAVs/ros/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/home/mavs/MAVs/ros/src/CMakeLists.txt" does not match the source "/home/febbo/Documents/workspace/MAVs/ros/src/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
Invoking "cmake" failed
Base path: /home/mavs/MAVs/ros
Source space: /home/mavs/MAVs/ros/src
Build space: /home/mavs/MAVs/ros/build
Devel space: /home/mavs/MAVs/ros/devel
Install space: /home/mavs/MAVs/ros/install
####
#### Running command: "cmake /home/mavs/MAVs/ros/src -DCATKIN_DEVEL_PREFIX=/home/mavs/MAVs/ros/devel -DCMAKE_INSTALL_PREFIX=/home/mavs/MAVs/ros/install -G Unix Makefiles" in "/home/mavs/MAVs/ros/build"
####
The command '/bin/sh -c /bin/bash -c 'source /opt/ros/kinetic/setup.bash; cd /home/$USERNAME/MAVs/ros/src; sudo rosdep init; rosdep update; catkin_init_workspace; cd ..; catkin_make'     && echo "source /home/$USERNAME/MAVs/ros/devel/setup.bash" >> /home/$USERNAME/.bashrc     && echo 'alias julia='/opt/julia-d386e40c17/bin/julia'' >> ~/.bashrc     && echo 'export PATH="$PATH:/opt/julia-d386e40c17/bin"' >>  ~/.bashrc' returned a non-zero code: 1
febbo@febbo-HP-Z220-SFF-Workstation:~/Documents/works
```

**Comment by huckl3b3rry87** [comment]
the fix is to delete the build folder on your local machine
![build](https://user-images.githubusercontent.com/8204378/48656349-514a9580-e9f2-11e8-8ca8-818f776a0dc0.png)

**Comment by yogeshwar-jadhav** [comment]
It didn't work even if I delete build file.

Base path: /home/yogeshwar/catkin_ws
Source space: /home/yogeshwar/catkin_ws/src
Build space: /home/yogeshwar/catkin_ws/build
Devel space: /home/yogeshwar/catkin_ws/devel
Install space: /home/yogeshwar/catkin_ws/install
####
#### Running command: "cmake /home/yogeshwar/catkin_ws/src -DCATKIN_DEVEL_PREFIX=/home/yogeshwar/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/home/yogeshwar/catkin_ws/install -G Unix Makefiles" in "/home/yogeshwar/catkin_ws/build"
####
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/yogeshwar/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/yogeshwar/catkin_ws/devel;/opt/ros/kinetic
-- This workspace overlays: /home/yogeshwar/catkin_ws/devel;/opt/ros/kinetic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.12", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/yogeshwar/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.12") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.20
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - rtabmap_ros
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'rtabmap_ros'
-- ==> add_subdirectory(rtabmap_ros)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Warning at rtabmap_ros/CMakeLists.txt:28 (find_package):
  By not providing "Findapriltag_ros.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "apriltag_ros", but CMake did not find one.

  Could not find a package configuration file provided by "apriltag_ros" with
  any of the following names:

    apriltag_rosConfig.cmake
    apriltag_ros-config.cmake

  Add the installation prefix of "apriltag_ros" to CMAKE_PREFIX_PATH or set
  "apriltag_ros_DIR" to a directory containing one of the above files.  If
  "apriltag_ros" provides a separate development package or SDK, be sure it
  has been installed.


CMake Error at rtabmap_ros/CMakeLists.txt:34 (find_package):
  Could not find a configuration file for package "RTABMap" that is
  compatible with requested version "0.19.5".

  The following configuration files were considered but not accepted:

    /opt/ros/kinetic/lib/i386-linux-gnu/rtabmap-0.19/RTABMapConfig.cmake, version: 0.19.3



-- Configuring incomplete, errors occurred!
See also "/home/yogeshwar/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/yogeshwar/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by huckl3b3rry87** [comment]
I suggest that you use docker
