### ISSUE TITLE
Demos

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaMPC/MAVs#31]
This issue is going to make sure that all demos are working on the master branch

# Demos
## roslaunch nloptcontrol_planner demo.launch
nloptcontrol_planner

## roslaunch system demoA.launch
obstacle_detector with vehicle_description
@tqshao can you please fix this?

### status = broken

```
[ INFO] [1521730529.026696899, 0.483000000]: "map" passed to lookupTransform argument target_frame does not exist.
[INFO] [1521730529.071362, 0.508000]: Spawn status: SpawnModel: Successfully spawned entity
[Obstacle2/spawn_obstacles-6] process has finished cleanly
log file: /home/febbo/.ros/log/0717f39a-2de1-11e8-8052-104a7d04da99/Obstacle2-spawn_obstacles-6*.log
[ INFO] [1521730529.252805167, 0.599000000]: "map" passed to lookupTransform argument target_frame does not exist.
[Obstacle1/spawn_obstacles-5] process has finished cleanly
log file: /home/febbo/.ros/log/0717f39a-2de1-11e8-8052-104a7d04da99/Obstacle1-spawn_obstacles-5*.log
[ INFO] [1521730529.431333339, 0.704000000]: "map" passed to lookupTransform argument target_frame does not exist.
```

## roslaunch system demoB.launch

nloptcontrol_planner with vehicle_description

### status = needs fix
I do not see the path that is being planned displayed in RViz
@tqshao can you please fix this?

## roslaunch system demoC.launch
vehicle_description and ros_base_planner

### status = needs fix
I do not see the path that is being planned displayed in RViz
@sumjos can you please fix this?

## roslaunch system demoD.launch
vehicle_description, ros_base_planner and chrono
@sumjos can you update this 
## roslaunch system demoE.launch
@tqshao can you please clarify this?
What is this demo showing? please make it clear in the top of the launch files like the rest of them

### status = needs fix

# Work Flow
Just update these demos with markdown and eventually they will serve as documentation

Thanks!

**Comment by huckl3b3rry87** [comment]
OK, I just finished making a bunch of the docs
https://juliampc.github.io/AVExamples.jl/latest/

All of the .md files can be found here
https://github.com/JuliaMPC/AVExamples.jl/tree/master/docs/src

Also, with everything. Make sure that it is correct. I will mention what I see is wrong, but make sure that everything else is still good. Also, please add pictures when appropriate. 

I am going to assign things to fix so that we can close this:


@sumjos 
- [ ] finish https://juliampc.github.io/AVExamples.jl/latest/packages/mavs_ros_planner/index.html
- [ ] add rviz display automatically https://juliampc.github.io/AVExamples.jl/latest/demos/system/demoC.html
- [ ] finish https://juliampc.github.io/AVExamples.jl/latest/demos/system/demoD.html
@sdhkr 
- [ ] finish https://juliampc.github.io/AVExamples.jl/latest/packages/ros_chrono/index.html
- [ ] finish https://juliampc.github.io/AVExamples.jl/latest/demos/ros_chrono/demo.html
@tqshao 
- [ ] do the flags and settings https://juliampc.github.io/AVExamples.jl/latest/packages/obstacle_detector/index.html
- [ ]  fix and finish https://juliampc.github.io/AVExamples.jl/latest/demos/system/demoA.html
- [ ] can you please add an riviz display for the trajectory here https://juliampc.github.io/AVExamples.jl/latest/demos/system/demoB.html
- [ ] finish https://juliampc.github.io/AVExamples.jl/latest/demos/system/demoE.html
@huckl3b3rry 
- [ ] finish https://juliampc.github.io/AVExamples.jl/latest/packages/vehicle_description/index.html
If you need to make a pull request for one of these please with my master and make small changes to fix it. 
- [ ] describe more https://juliampc.github.io/AVExamples.jl/latest/demos/system/demoF.html

If we can have these things done asap that would be great. I would like to maintain good documentation.

Thanks!

**Comment by sumjos** [comment]
@huckl3b3rry87 you can mark task 1,2 and 4, assigned to me, as completed. 
For task3(integration demoD) I am dependent on another pr from TQ, once I get to know about it, I will update you further

**Comment by shreysud** [comment]
@huckl3b3rry87  I have just completed the items on my list
