### ISSUE TITLE
Chrono Tire Model

### ISSUE THREAD

**Issue by shreysud** [JuliaMPC/MAVs#50]
Pacejka model loads, but vehicle behaves strangely.

### Description
The source code loads the Pacejka tire model and the simulation starts, but the tires bounce off of the ground and eventually the simulation ends with the same error: Assertion : m_Fz >0 failed. 
The tire model is specified in hmmwv_model.cpp code by the lines below. 

To see the issue, replace:
    RigidTire tire_front_left(rigid_tire_file);
    RigidTire tire_front_right(rigid_tire_file);
    RigidTire tire_rear_left(rigid_tire_file);
   RigidTire tire_rear_right(rigid_tire_file);

with:

ChPacejkaTire tire_front_left(pacejka_tire_file_left);
ChPacejkaTire tire_front_right(pacejka_tire_file_right);
ChPacejkaTire tire_rear_left(pacejka_tire_file_left);
ChPacejkaTire tire_rear_right(pacejka_tire_file_right);

The other tire models in data/vehicle/hmmwv/tire similarly do not perform well.

A better tire model needs to be used, or the parameters in hmmwv_pacejka.tir need to be tuned better.

**Comment by huckl3b3rry87** [comment]
fixed
