### ISSUE TITLE
demoA stuck itself

### ISSUE THREAD

**Issue by liukuanlk** [JuliaMPC/MAVs#63]

**Comment by liukuanlk** [comment]
I did the following steps:
1. clone the repo as:
`git clone https://github.com/JuliaMPC/MAVs`
2. install Docker ubuntu
3. install nvidia-docker. (Note: after installation, we may not be able to login the account. Because the nvidia-docker will install the latest version of GPU driver on the computer, which could cause incompatible. So I re-installed the nvidia driver 384)
4. build the docker 
`$ cd MAVs/docker
$ sh build.sh`
5. run default file
`# Default shared directory path is /home/$USER/shared_dir
$ sh run.sh`
6. run demo A
`roslaunch system demoA.launch`

**Comment by huckl3b3rry87** [comment]
Thank you. 

A few things:
1) when did you clone the project? I uploaded it last night.
2) try running the docker file in the folder (images/mavs_test)
2.a the steps will be the same as before, just do''sh run.sh''etc...

**Comment by huckl3b3rry87** [comment]
@liukuanlk did you try this?

**Comment by huckl3b3rry87** [comment]
Maybe a pycall issue https://github.com/JuliaPy/PyCall.jl/issues/565

**Comment by huckl3b3rry87** [comment]
Based off of the **limited information** that you provided me, it looks like you may be running into the issue that I warn about on the main README,md. Try this
```
sudo rm -r /home/mavs/.julia/.cache
```

**Comment by liukuanlk** [comment]
> Based off of the **limited information** that you provided me, it looks like you may be running into the issue that I warn about on the main README,md. Try this
> 
> ```
> sudo rm -r /home/mavs/.julia/.cache
> ```

Sure I'll try to run it tonight. Please leave the lab's door open if you can. Thanks!
