### ISSUE TITLE
Problem with sh build.sh

### ISSUE THREAD

**Issue by WeilinXu** [JuliaMPC/MAVs#64]
I installed nvidia driver, docker and nvidia docker successfully.
I run:
`$ cd MAVs/docker`
`$ sudo sh build.sh`
The build (last two colomn) seems to be successful:
```
Successfully built a09322f64455
Successfully tagged base:latest
```
**However, when I run:**
`$ sudo sh run.sh`

**The result and problem is**:

```
Shared directory: /home/root/shared_dir
Unable to find image 'mav:latest' locally
docker: Error response from daemon: pull access denied for mav, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

Although I have logged in:
`$ docker login`

```
Authenticating with existing credentials...
WARNING! Your password will be stored unencrypted in /home/ubuntu/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Login Succeeded

```
docker seems to work well:
`$ docker --version`

nvidia driver also works:
`$ nvidia-smi`
    
```
Tue Sep 18 22:12:06 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 950M    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   48C    P8    N/A /  N/A |    640MiB /  2004MiB |     20%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1255      G   /usr/lib/xorg/Xorg                           426MiB |
|    0      2378      G   compiz                                       178MiB |
|    0      3084      G   ...quest-channel-token=9315513773460001372    33MiB |
+-----------------------------------------------------------------------------+

```
nividia docker works, too:
`$ nvidia-docker --version`

`Docker version 18.06.1-ce, build e68fc7a
`

**Comment by huckl3b3rry87** [comment]
Try running without ''sudo". I.e ''sh build.sh'' and ''sh run.sh''

**Comment by huckl3b3rry87** [comment]
Also please check out some more docker commands. Like ''docker container la -a''

**Comment by huckl3b3rry87** [comment]
https://docs.docker.com/engine/reference/commandline/container_ls/

**Comment by WeilinXu** [comment]
> https://docs.docker.com/engine/reference/commandline/container_ls/

The results for command with and without `sudo` are the same.
There is no container related to MAVs, since it has never been built successfully.
The result for `docker image ls` is:
```
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
friendlyhello             latest              2064fd4c1d69        34 hours ago        132MB
t318forever/get-started   part2               2064fd4c1d69        34 hours ago        132MB
base                      latest              a09322f64455        2 days ago          8.65GB
osrf/ros                  kinetic-desktop     5723af5c7f65        7 days ago          2.32GB
hello-world               latest              4ab4c602aa5e        12 days ago         1.84kB
nvidia/cuda               latest              b17f13c2a1fd        2 weeks ago         1.96GB
python                    2.7-slim            c9cde4658340        2 weeks ago         120MB
```
There is no image named `mav:latest` either.

**Comment by huckl3b3rry87** [comment]
I think I know what happened. Try this
 1. try running the docker file in the folder (images/mavs_test)
1.a the steps will be the same as before, just do''sh run.sh''etc...i.e.
https://github.com/JuliaMPC/MAVs/tree/master/image/mavs_test

**Comment by huckl3b3rry87** [comment]
As I mentioned this is the dockerfile that I created last weekend. It should be more stable

**Comment by huckl3b3rry87** [comment]
Also please pull from the master again I just removed something that may have been causing 2. try running the docker file in the folder (images/mavs_test)
2.a the steps will be the same as before, just do''sh run.sh''etc...i.e.
https://github.com/JuliaMPC/MAVs/tree/master/image/mavs_test

**Comment by WeilinXu** [comment]
> Also please pull from the master again I just removed something that may have been causing an issue

I tried `sh build.sh` and `sh run.sh` in image/mavs_test, the output for run.sh is still the same.

**Comment by WeilinXu** [comment]
> did you pull from the master this morning?

@huckl3b3rry87 
I pulled it again around one hour ago

**Comment by huckl3b3rry87** [comment]
3

**Comment by WeilinXu** [comment]
The reason for the issue is that there is a typo at the end in run.sh, "mav" should be "mavs".
